apiVersion: v1
kind: Service
metadata:
  name: goargocd-app
spec:
  selector:
    app: goapp
  ports:
  - name: http
    protocol: TCP
    # port: 8089 # v1
    port: 8087 # latest
    # targetPort: 8089 # v1
    targetPort: 8087 # latest

